#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch case.foam

cp -avr zero/ 0/

runApplication chemkinToFoam \
               chemkin/chem.inp chemkin/therm.dat chemkin/transportProperties \
               constant/reactions constant/speciesThermo

runApplication blockMesh

runApplication renumberMesh -overwrite

# runApplication decomposePar

runApplication potentialFoam

# remove incompatible (volumetric) flux field
rm -f 0/phi

runApplication foamRun
#runApplication mpirun -np 8 foamRun -parallel

#------------------------------------------------------------------------------
