#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch case.foam

cp -avr zero/ 0/

runApplication chemkinToFoam \
               chemkin/chem.inp chemkin/therm.dat chemkin/transportProperties \
               constant/reactions constant/speciesThermo

runApplication blockMesh

runApplication renumberMesh -overwrite

# Copy files for running
cp constant/chemistryProperties.orig  constant/chemistryProperties
cp constant/combustionProperties.orig constant/combustionProperties

# Prepare for initial run.
foamDictionary constant/chemistryProperties \
    -entry chemistry       -set off
foamDictionary constant/combustionProperties \
    -entry combustionModel -set none
foamDictionary system/controlDict \
    -entry endTime         -set 100

runApplication potentialFoam

# remove incompatible (volumetric) flux field
rm -f 0/phi

# runApplication foamRun

ncores=32

if [ ! -f log.mpirun.1 ]; then
    runApplication decomposePar
    runApplication mpirun -np ${ncores} foamRun -parallel
    mv log.mpirun log.mpirun.1
fi

# Prepare for intermediate run.
foamDictionary constant/chemistryProperties \
    -entry chemistry       -set on
foamDictionary constant/combustionProperties \
    -entry combustionModel -set infinitelyFastChemistry
foamDictionary system/controlDict \
    -entry endTime         -set 1000

if [ ! -f log.mpirun.2 ]; then
    runApplication mpirun -np ${ncores} foamRun -parallel
    mv log.mpirun log.mpirun.2
fi

foamDictionary system/controlDict \
    -entry endTime         -set 100000

if [ ! -f log.mpirun.3 ]; then
    runApplication mpirun -np ${ncores} foamRun -parallel
    mv log.mpirun log.mpirun.3
fi

#------------------------------------------------------------------------------
