#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

updateProperties()
{
    foamDictionary constant/chemistryProperties \
        -entry chemistry       -set $1
    foamDictionary constant/combustionProperties \
        -entry combustionModel -set $2
    foamDictionary system/controlDict \
        -entry endTime         -set $3
}

prepareCase()
{
    touch case.foam

    cp -avr zero/ 0/
    cp constant/chemistryProperties.orig  constant/chemistryProperties
    cp constant/combustionProperties.orig constant/combustionProperties

    runApplication chemkinToFoam \
                chemkin/chem.inp \
                chemkin/therm.dat \
                chemkin/transportProperties \
                constant/reactions \
                constant/speciesThermo

    runApplication blockMesh
    runApplication renumberMesh -overwrite

    updateProperties off none 100
}

initializeFields()
{
    runApplication potentialFoam

    # Remove incompatible (volumetric) flux field
    rm -f 0/phi
}

runParallel()
{
    ncores=32
    runno=$1

    if [ ! -d processors$ncores ]; then
        runApplication decomposePar
    fi

    if [ ! -f log.mpirun.$runno ]; then
        runApplication mpirun -np ${ncores} foamRun -parallel
        mv log.mpirun log.mpirun.$runno
    fi
}

prepareCase

initializeFields

runParallel 1

updateProperties on infinitelyFastChemistry 200

runParallel 2

# runApplication reconstructPar -latestTime
# runApplication steadyParticleTracks
# runApplication foamToVTK

#------------------------------------------------------------------------------
