# Regenerative heat exchanger model

```{python}
%load_ext majordome.magic

import heat_recovery.thermocline as tc
import numpy as np
import sympy as sp

from majordome_engineering.transport import SolutionDimless
from heat_recovery.calculators import SkinFrictionFactor
from heat_recovery.calculators import WallGradingCalculator
from heat_recovery.thermocline import ThermoclineModel
```

In this section we present a simple model for the dimensioning of a thermocline energy storage system similar to a [regenerative heat exchanger](https://en.wikipedia.org/wiki/Regenerative_heat_exchanger). It is based on the use of hexagonal cells with circular holes as the solid matrix for the thermocline. The use of hexagonal cells allows for a high packing density and a large surface area for heat transfer; the calculation of the surface-to-volume ratio for this geometry is straightforward and presented in the end. It also includes the estimation of the number of cells in the cross section, thus the system diameter for a given total height and stored energy.

Other parameters relevant to the setup of a CFD simulation of the system are also estimated, such as the power per cell, the fluid injection velocity through the holes, and the associated Reynolds number. The model also includes a simple estimation of the pressure drop over the height, which is important for the design of the fluid injection system.

Below we present a summary of the parameters considered for the dimensioning of the system.

```{python}
model = ThermoclineModel("../model-cowper-like/dimensioning.yaml")

# ---------------------------------------------------------------------------

# m, absolute roughness of the hole wall
eps = 0.0002

# Relative roughness of the hole wall
rel = eps / model.num_D_h

# Friction factor:
f = 0.05

dp_calc = tc.PressureDropCalculator(model.num_h_t, model.num_D_h)

dp_charging = dp_calc.darcy_weisbach_pressure_drop(
    rho = model.num_rho_g_h,
    v   = model.fn_U_g(*model.args_charging),
    f   = f
)
dp_discharging = dp_calc.darcy_weisbach_pressure_drop(
    rho = model.num_rho_g_c,
    v   = model.fn_U_g(*model.args_discharging),
    f   = f
)

# ---------------------------------------------------------------------------

sol = SolutionDimless("airish.yaml")

y_p = model.num_y_plus
U_h = model.fn_U_g(*model.args_charging)
U_c = model.fn_U_g(*model.args_discharging)

sol.set_state(model.num_T_h, 101325, "N2: 0.79, O2: 0.21")
calc_h = WallGradingCalculator.from_solution(sol, L=model.num_D_h, U=U_h)

sol.set_state(model.num_T_c, 101325, "N2: 0.79, O2: 0.21")
calc_c = WallGradingCalculator.from_solution(sol, L=model.num_D_h, U=U_c)

def f_lam(Re):
    return SkinFrictionFactor.laminar(Re) / 8

def f_tur(Re):
    return SkinFrictionFactor.smooth_wall(Re, check=False) / 8

def evaluate_calc(calc):
    y_lam = 1000 * calc.first_layer(y_p, skin_factor=f_lam)
    y_tur = 1000 * calc.first_layer(y_p, skin_factor=f_tur)
    # print(f"Laminar {y_lam:.2f} mm | Turbulent {y_tur:.2f}")
    return y_lam, y_tur

evaluate_calc(calc_c)
y_cell = evaluate_calc(calc_h)[1] / 2

# ---------------------------------------------------------------------------

model.tabulate()
```


```{python}
%%md
The total required cross-sectional area of solid material in the thermocline $A_t$ is approximately ${model.fn_A_t(*model.args_charging):.1f}\:\mathrm{m^2}$.

$$
A_t = {sp.latex(model.A_t.simplify()):s}
$$

That requires a system diameter of {model.num_D_sys:.1f} m for the considered cell geometry and parameters. Dividing this by the cross-section of solid material in each hexagonal cell gives the number of cells per cross section, which allows for calculating the power per unit cell $P_c$ during charging to be ${model.fn_P_c(*model.args_charging):.0f}\:\mathrm{W}$ and discharging at ${model.fn_P_c(*model.args_discharging):.0f}\:\mathrm{W}$.

$$
P_c = {sp.latex(model.P_c.simplify()):s}
$$

That is equivalent to saying that there should be a total of ${model.fn_N_c(*model.args_charging):.0f}$ cells, with $N_c$ being given by

$$
N_c = {sp.latex(model.N_c.simplify()):s}
$$

During charging, the fluid injection velocity $U$ through the holes in the hexagonal cell is ${U_h:.1f}\:\mathrm{m\,s^{-1}}$, dropping to barely ${U_c:.1f}\:\mathrm{m\,s^{-1}}$ during discharging. That allows for calculating the Reynolds number for fluid flow through the holes in the hexagonal cell. For charging its value is estimated to be in the order of $Re_c \approx {model.fn_Re(*model.args_charging):.0f}$, while for discharging it drops to around $Re_d \approx {model.fn_Re(*model.args_discharging):.0f}$, characterizing a transitional flow regime that should transition to turbulent due to buoyancy effects. Assuming a $y_{+}={model.num_y_plus:.0f}$, one can estimate the first cell center to be at ${y_cell:.2f}\:\mathrm{mm}$, what would be adequate for use with a $k-\omega$ SST model.

$$
U = {sp.latex(model.U_g.simplify()):s}
$$

Assuming a roughness of {eps*1000:.1f} mm, thus a relative roughness of {rel:.3f} for the considered hole diameter. Pressure drop can be estimated using the Darcy-Weisbach equation to be in the order of {dp_charging/100:.0f} mbar during charging and {dp_discharging/100:.1f} mbar during discharging.

With the considered cell geometry, the surface-to-volume ratio $S_V$ of the hexagonal cell is ${model.fn_S_V(*model.args_charging):.3f}\:\mathrm{m^{-1}}$.

$$
S_V = {sp.latex(model.S_V.simplify()):s}
$$

Below we display the surface-to-volume ratio of the hexagonal cell as a function of the diameter of holes and the fraction of diameter representing wall thickness.
```

```{python}
#| fig-cap: Surface-to-volume ratio of the hexagonal cell
#| fig-align: center
#| out-width: 80%
p = tc.plot_surface_to_volume_ratio(model.cell_block)
```

Similarly, the pressure drop across the height of the thermocline can be estimated as a function of the diameter of holes and the fraction of diameter representing wall thickness. Below we display the pressure drop during charging as a function of these parameters.

```{python}
#| fig-cap: Pressure drop across the height of the thermocline during charging
#| fig-align: center
#| out-width: 80%
def dp_scan(D_h, m_h, f=f):
    # Heating is more critical:
    args = [
        # ThermoclineDescription
        model.num_H_t,
        model.num_h_t,
        model.num_T_h,
        model.num_T_c,
        # HexagonalCell
        D_h, # Overrides for funtion
        m_h, # Overrides for funtion
        # SolidMaterial
        model.num_rho_s,
        model.num_c_ps,
        model.num_k_s,
        # OperatingFluid
        model.num_h_g_c,
        model.num_h_g_h,
        # Charging parameters
        model.num_P_c,
        model.num_rho_g_h,
        model.num_mu_g_h
    ]

    rho = args[-2]
    v   = model.fn_U_g(*args)

    calc = tc.PressureDropCalculator(model.num_h_t, D_h)
    return calc.darcy_weisbach_pressure_drop(rho, v, f=f)

p = tc.plot_pressure_drop(dp_scan)
```
