#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import shutil
import sys

from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[2] / "script"))

from foamutils import Runner, Meshing, CommonProjectManager


def main(*args: Any) -> None:
    """ Execute main CLI workflow for the 2D OpenFOAM case. """
    obj = CommonProjectManager(
        root_dir    = HERE,
        how_to_mesh = how_to_mesh,
        how_to_run  = how_to_run,
    )

    obj(*args)


def how_to_mesh(args: Any) -> None:
    """ Manage the meshing workflow for the project. """
    def patching() -> None:
        """ Configure boundary patch types in boundary. """
        file = "constant/polyMesh/boundary"

        changes = [
            ("entry0/front/type",         "wedge"),
            ("entry0/back/type",          "wedge"),
            ("entry0/pipeInnerWall/type", "wall"),
            ("entry0/pipeOuterWall/type", "wall"),
            ("entry0/pipeEndWall/type",   "wall"),
            ("entry0/ductWalls/type",     "wall"),
        ]

        for entry, value in changes:
            Runner.dict_set_entry(file, entry, value)

    Path("case.foam").touch()

    Meshing.gmsh_to_foam_single_region(
        mesh_file = "constant/geometry/domain.msh",
        patching  = patching
    )


def how_to_run(args: Any) -> None:
    """ Manage the running workflow for the project. """
    def preprocess() -> None:
        """ Copy initial conditions from 0.orig to 0 directory. """
        zero_dir = Path("0")

        if zero_dir.exists():
            shutil.rmtree(zero_dir, ignore_errors=True)

        if Path("0.orig").exists():
            shutil.copytree("0.orig", zero_dir)

    def decomposing() -> None:
        """ Manage domain splitting edition for decomposition. """
        cores = args.cores

        dict_orig = Path("system/decomposeParDict.orig")
        dict_file = Path("system/decomposeParDict")

        if not dict_file.exists():
            shutil.copy(dict_orig, dict_file)

        match cores:
            case 4:
                n_coeffs = "(1 2 2)"
            case 20:
                n_coeffs = "(2 2 5)"
            case 32:
                n_coeffs = "(2 4 4)"
            case 40:
                n_coeffs = "(2 4 5)"
            case _:
                raise ValueError(f"Unsupported core count: {cores}")

        file = str(dict_file)
        Runner.dict_set_entry(file, "numberOfSubdomains", f"{cores}")
        Runner.dict_set_entry(file, "simpleCoeffs/n", n_coeffs)

    Path("case.foam").touch()

    Runner.foam_run(
        cores       = args.cores,
        reconstruct = args.reconstruct,
        preprocess  = preprocess,
        decomposing = decomposing,
        latest      = args.latest
    )


if __name__ == "__main__":
    main()
