project:
  type: book

execute:
  cache:   true
  echo:    false
  warning: false

book:
  title: "OpenFOAM Extensions"
  author: "Walter Dal'Maz Silva"
  date: "today"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2

  chapters:
    - index.md
    - CONTRIBUTING.md
    - CHANGELOG.md

    - part: Applications
      chapters:
        - applications/jmakLaplacianFoam/README.md

    - part: Libraries
      chapters:
        - src/lagrangian/index.md
        - src/thermophysicalModels/index.md

format:
  html:
    reference-location: document
    highlight-style: github
    theme:
      - pulse

  typst: default
