#!/usr/bin/env bash

# =====================================================================
# Configurations
# =====================================================================

# Run from this directory
cd ${0%/*} || exit 1

# Get path to this directory:
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source repository tools:
. "$SCRIPT_DIR/etc/bashrc"

# Parse arguments for library compilation:
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# Ensure minimum environment is present:
bootstrapToolbox

# =====================================================================
# Workflow
# =====================================================================

header_bold_green "Starting compilation..."

message_bold_yellow "> Compiling applications..."
(
    wmake applications/jmakLaplacianFoam
) > log.makeApplications

message_bold_yellow "> Compiling libraries..."
(
    src/Allwmake $targetType $*
) > log.makeLibraries

# =====================================================================
# Post-workflow
# =====================================================================

header_bold_green "Check applications under $FOAM_USER_APPBIN"
message_red "$(ls -hl $FOAM_USER_APPBIN)"

header_bold_green "Check libraries under $FOAM_USER_LIBBIN"
message_red "$(ls -hl $FOAM_USER_LIBBIN)"

# =====================================================================
# EOF
# =====================================================================
