#!/usr/bin/env bash

# Run from this directory:
cd ${0%/*} || exit 1

find . \
    -mindepth 1 -maxdepth 1 -type d \
	-regextype posix-extended \
	-regex './[0-9]+' \
	-exec rm -rf -- {} +

rm -rf 0/
rm -rf constant/extendedFeatureEdgeMesh/
rm -rf constant/geometry/*.eMesh
rm -rf constant/polyMesh/
rm -rf postProcessing/
rm -rf case.foam
rm -rf log.*