#!/usr/bin/env bash

# XXX keep this here so that this script can be used manually:
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Clean from a previous run:
rm -rf log.decomposePar

# Configure decomposeParDict based on selected core count
file="system/decomposeParDict"

if [ "$CORES" = "4" ]; then
    foamDictionary "$file" -entry numberOfSubdomains -set 4
    foamDictionary "$file" -entry simpleCoeffs/n -set "(1 2 2)"
elif [ "$CORES" = "20" ]; then
    foamDictionary "$file" -entry numberOfSubdomains -set 20
    foamDictionary "$file" -entry simpleCoeffs/n -set "(2 2 5)"
elif [ "$CORES" = "32" ]; then
    foamDictionary "$file" -entry numberOfSubdomains -set 32
    foamDictionary "$file" -entry simpleCoeffs/n -set "(2 4 4)"
else
    echo "Unsupported core count: $CORES"
    exit 1
fi

# Decompose domain
runApplication decomposePar
