#!/usr/bin/env bash

# Run from this directory
cd ${0%/*} || exit 1

# Wheter to start from scratch or restart from previous case
mode="restart"

# Whether to consider buoyancy effects or not
buoyancy="no buoyancy"

# Select number of cores to use for parallel run
export NUM_PROCS=6

function generateMesh {
    if [ -d "constant/fluid/polyMesh" ]; then
        echo "Mesh already exists. Skipping mesh generation."
        return
    fi

    python3 model.py

    gmshToFoam mesh.msh

    createPatch

    renumberMesh

    splitMeshRegions -cellZones

    rm -rf constant/polyMesh

    checkMesh -region fluid
    checkMesh -region solid
}

function initializeCase {
    if [ "$mode" = "restart" ]; then
        mkdir -p 0.00000000e+00/{fluid,solid}
        cp ../03-fluid-only/2.00000000e+00/* 0.00000000e+00/fluid

        fname="0.00000000e+00/fluid/T"
        where="boundaryField/fluid_to_solid"

        foamDictionary $fname -entry $where/type -set coupledTemperature
        foamDictionary $fname -entry $where/value -set 'uniform 300'

        if [ "$buoyancy" != "buoyancy" ]; then
            rm -rf 0.00000000e+00/fluid/p_rgh
        fi
    else
        foamDictionary 0.orig/fluid/p      -expand > 0.00000000e+00/fluid/p
        foamDictionary 0.orig/fluid/T      -expand > 0.00000000e+00/fluid/T
        foamDictionary 0.orig/fluid/U      -expand > 0.00000000e+00/fluid/U
        foamDictionary 0.orig/fluid/alphat -expand > 0.00000000e+00/fluid/alphat
        foamDictionary 0.orig/fluid/nut    -expand > 0.00000000e+00/fluid/nut
        foamDictionary 0.orig/fluid/k      -expand > 0.00000000e+00/fluid/k
        foamDictionary 0.orig/fluid/omega  -expand > 0.00000000e+00/fluid/omega

        if [ "$buoyancy" = "buoyancy" ]; then
            foamDictionary 0.orig/p_rgh  -expand > 0.00000000e+00/fluid/p_rgh
        fi
    fi

    # Expand solid temperature field to actual mesh
    foamDictionary 0.orig/solid/T -expand > 0.00000000e+00/solid/T
}

function runCase {
    # Run the case in parallel
    decomposePar -allRegions
    mpiexec -n $NUM_PROCS foamMultiRun -parallel > log.foamMultiRun

    # Reconstruct the results of final time step
    reconstructPar -latestTime

    # Generate logs for post-processing
    foamLog log.foamMultiRun
}

generateMesh
initializeCase
runCase
