#!/usr/bin/env bash

# Run from this directory
cd ${0%/*} || exit 1

# Wheter to start from scratch or restart from previous case
mode="restart"

# Select number of cores to use for parallel run
export NUM_PROCS=20


if [ "$mode" = "restart" ]; then
    cp ../03-fluid-only/2.00000000e+00/* 0.00000000e+00/fluid

    fname="0.00000000e+00/fluid/T"
    where="boundaryField/fluid_to_solid/type"
    foamDictionary $fname -entry $where -set coupledTemperature
    # TODO value
else
    foamDictionary 0.orig/p      -expand > 0.00000000e+00/p
    foamDictionary 0.orig/T      -expand > 0.00000000e+00/T
    foamDictionary 0.orig/U      -expand > 0.00000000e+00/U
    foamDictionary 0.orig/alphat -expand > 0.00000000e+00/alphat
    foamDictionary 0.orig/nut    -expand > 0.00000000e+00/nut
    foamDictionary 0.orig/k      -expand > 0.00000000e+00/k
    foamDictionary 0.orig/omega  -expand > 0.00000000e+00/omega
    foamDictionary 0.orig/p_rgh  -expand > 0.00000000e+00/p_rgh
fi

# Expand solid temperature field to actual mesh
foamDictionary 0.orig/solid/T -expand > 0.00000000e+00/solid/T

# Run the case in parallel
decomposePar
mpiexec -n $NUM_PROCS foamMultiRun -parallel > log.foamMultiRun

# Reconstruct the results of final time step
reconstructPar -latestTime

# Generate logs for post-processing
foamLog log.foamMultiRun
