#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch case.foam

cp -avr zero/* .
cp ../components/blockMeshDict system/
cp ../components/fv* system/
cp ../components/Allclean .

runApplication blockMesh
runApplication potentialFoam
runApplication foamRun

cp "postProcessing/residuals(p,U,k,epsilon)/0/residuals.dat" residuals.ref

#------------------------------------------------------------------------------
