#!/usr/bin/env bash

# Run from this directory:
cd ${0%/*} || exit 1

# Source tutorial clean functions:
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf 0/
rm -rf *.log
rm -rf *.msh
rm -rf *.pdf
rm -rf chemkin/media/
rm -rf chemkin/reactions.inp
rm -rf chemkin/thermo.dat
rm -rf chemkin/transport*

#------------------------------------------------------------------------------