#!/usr/bin/env bash

# Run from this directory:
cd ${0%/*} || exit 1

# Source tutorial run functions:
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Make sure mesh exists:
if [ ! -d "constant/polyMesh" ]; then
    ./domain.sh
fi

# To open with ParaView:
touch case.foam

if [ ! -d "200" ]; then
    # Copy initial conditions:
    cp -r 0.orig/ 0/

    # Decompose the domain:
    runApplication decomposePar
    mv log.decomposePar log.decomposePar.1

    # Run the simulation:
    runParallel foamRun
    mv log.foamRun log.foamRun.1

    # Reconstruct the solution:
    runApplication reconstructPar -latestTime
    mv log.reconstructPar log.reconstructPar.1

    # Remove decomposition files:
    rm -rf processor*

    # Make spark for combustion:
    runApplication setFields -latestTime
fi

# Extend time:
file=system/controlDict
foamDictionary $file -entry endTime -set 10000 > /dev/null

# Parameterize compatible with combustion:
file=system/fvSolution
foamDictionary $file -entry PIMPLE/maxCo    -set 0.5 > /dev/null
foamDictionary $file -entry PIMPLE/Yref/CH4 -set 0.1 > /dev/null
foamDictionary $file -entry PIMPLE/Yref/O2  -set 0.1 > /dev/null

# Decompose the domain:
runApplication decomposePar
mv log.decomposePar log.decomposePar.2

# Run the simulation:
runParallel foamRun
mv log.foamRun log.foamRun.2

#------------------------------------------------------------------------------