#!/usr/bin/env bash

set -e

#region: general setup
# Run from this directory:
cd ${0%/*} || exit 1

# Set local OpenFOAM extensions path:
export FOAM_USER_RC=$(realpath "../../../etc/bashrc")

# Source local OpenFOAM extensions:
. "${FOAM_USER_RC}"

# Source tutorial run functions:
. $WM_PROJECT_DIR/bin/tools/RunFunctions
#endregion

#region: workflow functions
function prepareDomainMesh() {
    if [ -d "constant/polyMesh" ]; then
        echo "Mesh already exists, skipping..."
    else
        # Generate the base mesh:
        uv run python domain.py > log.mesh

        # Convert base Gmsh mesh to OpenFOAM:
        runApplication gmshToFoam domain.msh

        # Perform preliminary renumbering:
        runApplication renumberMesh

        # Fix patch types after splitting:
        file=constant/polyMesh/boundary
        foamDictionary $file -entry entry0/back/type  -set wedge > /dev/null
        foamDictionary $file -entry entry0/front/type -set wedge > /dev/null
        foamDictionary $file -entry entry0/walls/type -set wall  > /dev/null

        # Check mesh:
        runApplication checkMesh
    fi
}

function runAndReconstructStep() {
    local tend=$1
    local step=$2

    # Decompose the domain:
    runApplication decomposePar
    mv log.decomposePar log.decomposePar.$step

    # Run the simulation:
    runParallel foamRun
    mv log.foamRun log.foamRun.$step

    # Reconstruct the solution:
    runApplication reconstructPar -latestTime
    mv log.reconstructPar log.reconstructPar.$step

    # Remove decomposition files:
    rm -rf processor*
}

function runFlowAlone() {
    local tend=$1

    if [ -d "$tend" ]; then
        echo "Run 1 already completed"
    else
        # Ensure consistent end-time:
        file=system/controlDict
        foamDictionary $file -entry endTime -set $tend > /dev/null

        runAndReconstructStep $tend "1"
    fi
}

function runLowOrderOde() {
    local tend=$1

    if [ -d "$tend" ]; then
        echo "Run 2 already completed"
    else
        # Make spark for combustion:
        runApplication setFields -latestTime

        # Extend time:
        file=system/controlDict
        foamDictionary $file -entry endTime -set $tend > /dev/null

        # Parameterize compatible with combustion:
        file=system/fvSolution
        foamDictionary $file -entry PIMPLE/maxCo     -set 0.50 > /dev/null
        foamDictionary $file -entry PIMPLE/alphaY    -set 0.20 > /dev/null
        foamDictionary $file -entry PIMPLE/alphaTemp -set 0.20 > /dev/null
        foamDictionary $file -entry PIMPLE/Yref/CH4  -set 0.10 > /dev/null
        foamDictionary $file -entry PIMPLE/Yref/O2   -set 0.10 > /dev/null

        runAndReconstructStep $tend "2"
    fi
}

function runHighOrderOde() {
    local tend=$1

    if [ -d "$tend" ]; then
        echo "Run 3 already completed"
    else
        # Extend time:
        file=system/controlDict
        foamDictionary $file -entry endTime -set $tend > /dev/null

        # Parameterize compatible with combustion:
        file=system/fvSolution
        foamDictionary $file -entry PIMPLE/maxCo     -set 1.0 > /dev/null

        # Move to a higher order solver:
        file=constant/chemistryProperties
        foamDictionary $file -entry odeCoeffs/solver -set rodas34 > /dev/null
        foamDictionary $file -entry odeCoeffs/relTol -set 1.0e-03 > /dev/null

        runAndReconstructStep $tend "3"
    fi
}

function mainWorkflow() {
    local case=$1
    local temp=$2

    local target="solution.$case"

    # Prepare _shared with current temperature:
    uv run python initialize.py --temperature $temp

    # Copy files:
    mkdir -p "$target"
    cp -r 0.orig   "$target/0"
    cp -r system   "$target/system"
    cp -r constant "$target/constant"

    # Create case.foam:
    touch "$target/case.foam"

    # Run simulations:
    pushd $target > /dev/null
    runFlowAlone    "$3"
    runLowOrderOde  "$4"
    runHighOrderOde "$5"
    popd > /dev/null
}
#endregion

prepareDomainMesh

#  ......... case  T    iter_1 iter_2 iter_3
mainWorkflow 1     25   5000   15000  30000
mainWorkflow 2     300  5000   10000  20000

#------------------------------------------------------------------------------