#!/usr/bin/env bash

# Run from this directory:
cd ${0%/*} || exit 1

# Source tutorial run functions:
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Make sure mesh exists:
if [ ! -d "constant/polyMesh" ]; then
    ./domain.sh
fi

# To open with ParaView:
touch case.foam

# Copy initial conditions:
cp -r 0.orig 0

# Run the simulation:
runApplication foamRun

# Make spark for combustion:
runApplication setFields

# Extend time:
file=system/controlDict
foamDictionary $file -entry endTime -set 10000 > /dev/null

# Reduce Courant number:
file=system/fvSolution
foamDictionary $file -entry PIMPLE/maxCo -set 0.5 > /dev/null

# Run the simulation:
runApplication foamRun

#------------------------------------------------------------------------------