#!/usr/bin/env bash

set -e

# Run from this directory:
cd ${0%/*} || exit 1

step=2

orig=restart.3
target=solution.$step

rm -rf $target
mkdir -p $target/{constant,system}
touch $target/case.foam

cp -r $orig/             $target/0
cp -r postProcessing/    $target/postProcessing/
cp -r constant/polyMesh  $target/constant/
cp system/controlDict    $target/system/
