#!/usr/bin/env bash

# Run from this directory:
cd ${0%/*} || exit 1

# Generated data:
rm -rf chemkin/media/
rm -rf chemkin/reactions
rm -rf chemkin/thermo
rm -rf chemkin/thermo.dat
rm -rf chemkin/transport

# Logs and mesh at root:
rm -rf log.*
rm -rf *.msh

# Logs and mesh under model:
rm -rf model/log.*
rm -rf model/constant/polyMesh
rm -rf model/constant/initialConditions

# Solutions:
rm -rf solution.*/

#------------------------------------------------------------------------------