#!/usr/bin/env bash

#region: general setup
# Exit on error:
set -e

# Run from this directory:
cd ${0%/*} || exit 1

# Source local OpenFOAM extensions:
. "$(realpath "../../../etc/bashrc")"
#endregion

#region: workflow functions
function prepareDomainMesh() {
    if [ -d "model/constant/polyMesh" ]; then
        echo "Mesh already exists, skipping..."
        return 0
    fi

    # Generate the base mesh:
    uv run python domain.py > log.mesh

    ( # Meshing inside model/
        cd model/

        # Convert base Gmsh mesh to OpenFOAM:
        runApplication gmshToFoam ../domain.msh

        # Fix patch types before going forward:
        file=constant/polyMesh/boundary
        foamDictionary $file -entry entry0/back/type  -set wedge > /dev/null
        foamDictionary $file -entry entry0/front/type -set wedge > /dev/null
        foamDictionary $file -entry entry0/walls/type -set wall  > /dev/null

        # Perform preliminary renumbering (skipping 0/ directory fields):
        runApplication renumberMesh -noZero

        # Check mesh:
        runApplication checkMesh
    )

}

function runDevelopFlow() {
    local tend=$1

    if [ -d "$tend" ]; then
        echo "Run already completed up to $tend"
        return 0
    fi
}

function runFlameIgnition() {
    local tend=$1

    if [ -d "$tend" ]; then
        echo "Run already completed up to $tend"
        return 0
    fi
}

function runSmoothConvergence() {
    local tend=$1

    if [ -d "$tend" ]; then
        echo "Run already completed up to $tend"
        return 0
    fi
}

function mainWorkflow() {
    local case=$1
    local power=$2
    local temperature=$3
    local target="solution.$case"

    # Make sure there is a mesh to copy:
    prepareDomainMesh

    # Prepare case conditions:
    uv run python project.py --power $power --temperature $temperature

    # Copy case if not already started:
    if [ ! -d "$target/" ]; then
        cp -r model/ "$target/"
    fi

    # Create case.foam:
    touch "$target/case.foam"

    # Run simulations:
    pushd $target > /dev/null
    runDevelopFlow       "$4"
    runFlameIgnition     "$5"
    runSmoothConvergence "$6"
    popd > /dev/null
}
#endregion

# .......... case  power  T   end1  end2  end3
mainWorkflow 1     1000   25  1000  2000  5000

#------------------------------------------------------------------------------