#!/usr/bin/env bash

#region: general setup
# Exit on error:
set -e

# Run from this directory:
cd ${0%/*} || exit 1

# Source local OpenFOAM extensions:
. "$(realpath "../../../etc/bashrc")"
#endregion

#region: workflow functions
function prepareDomainMesh() {
    if [ -d "model/constant/polyMesh" ]; then
        echo "Mesh already exists, skipping..."
    else
        # Generate the base mesh:
        uv run python domain.py > log.mesh

        ( # Meshing inside model/
            cd model/

            # Convert base Gmsh mesh to OpenFOAM:
            runApplication gmshToFoam ../domain.msh

            # Perform preliminary renumbering:
            runApplication renumberMesh

            # Fix patch types after splitting:
            file=constant/polyMesh/boundary
            foamDictionary $file -entry entry0/back/type  -set wedge > /dev/null
            foamDictionary $file -entry entry0/front/type -set wedge > /dev/null
            foamDictionary $file -entry entry0/walls/type -set wall  > /dev/null

            # Check mesh:
            runApplication checkMesh
        )
    fi
}

function runFlowAlone() {
    local tend=$1

    if [ -d "$tend" ]; then
        echo "Run 1 already completed"
    else
        # Ensure consistent end-time:
        file=system/controlDict
        foamDictionary $file -entry endTime -set $tend > /dev/null

        runAndReconstructStep
    fi
}

function runLowOrderOde() {
    local tend=$1

    if [ -d "$tend" ]; then
        echo "Run 2 already completed"
    else
        # Make spark for combustion:
        runApplication setFields -latestTime

        # Extend time:
        file=system/controlDict
        foamDictionary $file -entry endTime -set $tend > /dev/null

        # Parameterize compatible with combustion:
        file=system/fvSolution
        foamDictionary $file -entry PIMPLE/maxCo     -set 3.00 > /dev/null
        foamDictionary $file -entry PIMPLE/alphaY    -set 0.20 > /dev/null
        foamDictionary $file -entry PIMPLE/alphaTemp -set 0.20 > /dev/null
        foamDictionary $file -entry PIMPLE/Yref/CH4  -set 0.20 > /dev/null
        foamDictionary $file -entry PIMPLE/Yref/O2   -set 0.20 > /dev/null

        runAndReconstructStep
    fi
}

function runHighOrderOde() {
    local tend=$1

    if [ -d "$tend" ]; then
        echo "Run 3 already completed"
    else
        # Extend time:
        file=system/controlDict
        foamDictionary $file -entry endTime -set $tend > /dev/null

        # Parameterize compatible with combustion:
        file=system/fvSolution
        foamDictionary $file -entry PIMPLE/maxCo     -set 1.0 > /dev/null

        # Move to a higher order solver:
        file=constant/chemistryProperties
        # foamDictionary $file -entry odeCoeffs/solver -set rodas34 > /dev/null
        foamDictionary $file -entry odeCoeffs/relTol -set 1.0e-03 > /dev/null

        runAndReconstructStep
    fi
}

function mainWorkflow() {
    local case=$1
    local temp=$2

    local target="solution.$case"

    # Prepare _shared with current temperature:
    uv run python project.py --temperature $temp

    # Copy case if not already started:
    if [ ! -d "$target/" ]; then
        cp -r model/ "$target/"
    fi

    # Create case.foam:
    touch "$target/case.foam"

    # Run simulations:
    pushd $target > /dev/null
    runFlowAlone    "$3"
    runLowOrderOde  "$4"
    runHighOrderOde "$5"
    popd > /dev/null
}
#endregion

prepareDomainMesh

#  ......... case  T    iter_1 iter_2 iter_3
mainWorkflow 1     25   1000   5000  10000
# mainWorkflow 2     300  5000   10000  20000

#------------------------------------------------------------------------------