#!/usr/bin/env bash

# Run from this directory
cd ${0%/*} || exit 1

rm -rf 0.00000000e+00
rm -rf constant/polyMesh/
rm -rf constant/cellToRegion
rm -rf constant/block/polyMesh/
rm -rf constant/media/polyMesh/

# rm -rf log.*
# rm -rf logs
# rm -rf postProcessing
# rm -rf processor*
# rm -rf constant/userParameters


#------------------------------------------------------------------------------
