= Introduction <chapter-1>

Computational fluid dynamics workflows progress sequentially through geometry definition, spatial discretization, numerical setup, solver monitoring, and post-processing. While the numerical solution of the governing equations is handled autonomously by computing hardware, configuring the domain, initial conditions, physical parameters, and numerical schemes relies entirely on user input. Within this complete pipeline, geometry handling and grid generation represent the most labor-intensive stages, frequently consuming up to eighty percent of an engineer's active working time. Because numerical solvers are fundamentally constrained by spatial discretization, the quality of the resulting mesh establishes the mathematical foundation for the entire simulation. An improperly constructed mesh produces severe numerical errors, instability, or non-physical results, embodying the principle of _garbage in, garbage out_. Conversely, achieving a robust and physically representative grid allows practitioners to maintain strict control over solution accuracy and solver stability.

== Meshing and tool selection in OpenFOAM

OpenFOAM provides native meshing utilities designed for varying levels of geometric complexity. For elementary configurations such as simple channels, square ducts, or basic geometric blocks, the standard `blockMesh` utility offers an efficient and straightforward solution. However, utilizing `blockMesh` for intricate, highly detailed engineering surfaces becomes prohibitively complex and impractical. To accommodate complex geometries, `snappyHexMesh` serves as the primary discretization tool within the native OpenFOAM framework. While external commercial or third-party open-source meshing packages can generate grids for subsequent conversion into OpenFOAM format, `snappyHexMesh` provides a tightly integrated, scriptable alternative.

The operation of `snappyHexMesh` is intrinsically linked to `blockMesh`. Rather than generating a grid entirely from scratch, `snappyHexMesh` operates as a _top-to-bottom_, hexahedral-dominant Cartesian meshing utility. It mandates a pre-existing background mesh, typically constructed using `blockMesh`, which serves as a coarse volumetric template containing the target geometry. The background grid should consist of pure hexahedral cells in the domain regions intersecting the geometry, maintaining a uniform aspect ratio close to unity. Starting from this template, `snappyHexMesh` refines the base volume downward toward the boundaries of the imported surface model.

== Core principles and spatial discretization

Several governing principles define the operational behavior of `snappyHexMesh`. First, `snappyHexMesh` is strictly a three-dimensional meshing utility. It cannot natively construct two-dimensional grids directly. Two-dimensional simulations must be generated by first meshing a one-cell-thick three-dimensional domain and subsequently converting or collapsing it through an independent post-processing utility.

Second, spatial resolution is governed through relative _octree refinement_ rather than explicit target dimensions. Instead of specifying an absolute edge length in spatial coordinates, refinement levels are defined relative to the background cell size produced by `blockMesh`. An octree data structure divides a parent hexahedral cell into eight smaller hexahedra at refinement level one, sixty-four cells at level two, and continues dividing along a strict two-to-one volumetric splitting ratio. Because cell density scales exponentially with higher refinement levels, careful control of local refinement parameters and global cell limits is essential to prevent excessive memory overhead and computational bottlenecks.

== The `snappyHexMesh` workflow and configuration

The `snappyHexMesh` execution process is text-driven and controlled through an input configuration file designated as `snappyHexMeshDict`, located within the `system/` directory of the simulation case. Native execution does not rely on an officially supported graphical user interface, requiring users to interact directly with command-line instructions and dictionary files. Although the master dictionary exposes more than seventy distinct configuration keywords, standard setups rely on a core subset of parameters while retaining default values for secondary options. It partitions the meshing process into three sequential and modular phases:

1. The first phase is castellation, during which the background Cartesian grid is iteratively refined according to user-defined geometric entities, surface features, and spatial regions. Cells located outside the active simulation domain, determined via a specified coordinate point, are systematically removed, producing a mathematically valid but step-like Cartesian mesh.

2. The second phase is snapping, where the jagged cell vertices of the castellated mesh are projected and smoothed onto the CAD surface boundaries to construct a body-fitted interface necessary for accurate aerodynamic and hydrodynamic force calculations.

3. The third phase is boundary layer inflation, which introduces thin, highly resolved prismatic cell layers along specified solid boundaries to accurately resolve near-wall boundary layer physics and turbulent gradients.

These three execution phases are governed by individual boolean switches at the beginning of the dictionary, as illustrated in the global structure of `snappyHexMeshDict` is provided in @lst-snappyhexmesh-structure. Because the steps operate independently, users can selectively run and inspect the castellated mesh before initiating the snapping or layer addition routines, facilitating iterative troubleshooting and optimization. In practice, most of the time the castellation and snapping will be activated together at once, while the boundary layer will be activated later as all refinement stages are completed. Throughout all meshing stages, the utility continuously evaluates and enforces explicit geometric quality criteria to maintain numerical validity and solver stability.

#figure(
```cpp
// Headers ...

castellatedMesh true;
snap            true;
addLayers       true;

geometry
{}

castellatedMeshControls
{}

snapControls
{}

addLayersControls
{}
```,
caption: [General structure of `snappyHexMeshDict`.],
) <lst-snappyhexmesh-structure>

// EOF