#!/usr/bin/env bash

# Run from this directory
cd ${0%/*} || exit 1

if [ ! -d "01-fluid-only/postProcessing" ]; then
    (
        cd 01-fluid-only || exit 1
        ./Allclean
        ./Allrun
    )
fi

if [ ! -d "02-fluid-only/postProcessing" ]; then
    (
        cd 02-fluid-only || exit 1
        ./Allclean
        ./Allrun
    )
fi

# if [ ! -d "03-fluid-only/postProcessing" ]; then
#     (
#         cd 03-fluid-only || exit 1
#         ./Allclean
#         ./Allrun
#     )
# fi

if [ ! -d "04-fluid-solid/postProcessing" ]; then
    (
        cd 04-fluid-solid || exit 1
        ./Allclean
        ./Allrun
    )
fi
