---
title: "Regenerative Heat Exchanger Tutorial"
author: "Walter Dal'Maz Silva"
date: today

bibliography: https://raw.githubusercontent.com/wallytutor/kompanion/refs/heads/main/notes/references.bib

toc: true
toc-depth: 2

format:
  pdf:
    reference-location: document
    highlight-style: github
    documentclass: scrreprt
    papersize: a4
    fontsize: 11pt
    mainfont: "Latin Modern Sans"
    sansfont: "Latin Modern Sans"
    geometry:
      - margin=25mm
---

# Introduction {.unnumbered}

In this tutorial we will go through the steps to create a regenerative heat exchanger case in OpenFOAM. We will start by generating the geometry and mesh using Gmsh, then we will set up the case for a fluid-only simulation, and finally we will add the solid region to create a coupled fluid-solid case. The steps are decomposed into:

- `01-fluid-only/`: establish a fluid-only case for initialization of flow pattern. This is a minimalistic case, mostly focused on getting a basic flow solution for testing the mesh quickly.

- `02-fluid-only/`: include turbulence in the fluid-only case. This is the case that should be used for the final fluid-only solution, which will be used as initial condition for the coupled case.

::: {.callout-note title="Generating a new mesh"}

Please notice generating a new mesh, you should manually clean the `01-fluid-only` case and residuals in the project root. That means:

- Delete the `constant/polyMesh` and `0.00000000e+00` directories.
- Delete any `.tar.xz` file and any residual `mesh.msh`  from a previous run

This is intentional to ensure that the new mesh is created on intention, and to prevent accidental overwriting of existing data.

:::

# Environment setup

Before starting, we import all required tools and libraries. It is simpler to track the environment when everything is imported in one place.

```{python}
#| echo: true
%load_ext majordome.magic

import os
import shutil
import sys
import tarfile
import numpy as np
import sympy as sp
import pyvista as pv
from pathlib import Path
from subprocess import run
from majordome.engineering import SolutionDimless
from majordome.engineering import SkinFrictionFactor
from majordome.engineering import WallGradingCalculator
from ruamel.yaml import YAML

import heat_recovery.thermocline as tc
from heat_recovery.cowper_like import CowperLikeGeometry
from heat_recovery.cowper_like import PostProcessing
from heat_recovery.thermocline import ThermoclineModel

pv.set_jupyter_backend("static")
```

```{python}
#| echo: false
# If running in a Jupyter notebook, __file__ is not defined, so we use
# the current working directory as the base path. If running as a script,
# we use the directory of the script as the base path. This allows us to
# have a consistent reference point for file paths regardless of the
# execution environment.
try:
    HERE = Path(__file__).parent
except NameError:
    HERE = Path(os.getcwd())

# print(f"Base path: {HERE}")
```

::: {.callout-note title="Environment variables"}

All cases require a `NUM_PROCS` environment variable to be set. This is used to set the number of processors for parallel runs. By default, we set it to 4, but you can change it based on your system capabilities.

```{python}
#| echo: true
ENV = os.environ.copy()
ENV["NUM_PROCS"] = "4"
```

:::

Below we provide a standard function that will be used to run commands in the terminal with the correct environment. This is a utility function that will be used throughout the tutorial. It ensures that the commands are executed in the correct environment and that the output is logged for later inspection.

```{python}
#| echo: true
def runner(cmd, wdir: str = None) -> None:
    """ Run a command in the terminal with the correct environment. """
    with open("log.model", "a") as f:
        run(cmd, env=ENV, check=True, stdout=f, stderr=f, cwd=wdir)
```

Some pervasive variables used across the tutorial: the configuration file with the heat exchanger paramenters, and the name of the mesh file to be generated.

```{python}
#| echo: true
config = "dimensioning.yaml"
mesh   = "mesh.msh"
```

# System dimensioning

::: {.callout-note title="To-do"}

Review this section and break down in a more didactic way.

:::

In this section we present a simple model for the dimensioning of a thermocline energy storage system similar to a [regenerative heat exchanger](https://en.wikipedia.org/wiki/Regenerative_heat_exchanger). It is based on the use of hexagonal cells with circular holes as the solid matrix for the thermocline. The use of hexagonal cells allows for a high packing density and a large surface area for heat transfer; the calculation of the surface-to-volume ratio for this geometry is straightforward and presented in the end. It also includes the estimation of the number of cells in the cross section, thus the system diameter for a given total height and stored energy.

Other parameters relevant to the setup of a CFD simulation of the system are also estimated, such as the power per cell, the fluid injection velocity through the holes, and the associated Reynolds number. The model also includes a simple estimation of the pressure drop over the height, which is important for the design of the fluid injection system.


## Summary of parameters

Below we present a summary of the parameters considered for the dimensioning of the system.

```{python}
model = ThermoclineModel(config)

# ---------------------------------------------------------------------------

# m, absolute roughness of the hole wall
eps = 0.0002

# Relative roughness of the hole wall
rel = eps / model.num_D_h

# Friction factor:
f = 0.05

dp_calc = tc.PressureDropCalculator(model.num_h_t, model.num_D_h)

dp_charging = dp_calc.darcy_weisbach_pressure_drop(
    rho = model.num_rho_g_h,
    v   = model.fn_U_g(*model.args_charging),
    f   = f
)
dp_discharging = dp_calc.darcy_weisbach_pressure_drop(
    rho = model.num_rho_g_c,
    v   = model.fn_U_g(*model.args_discharging),
    f   = f
)

# ---------------------------------------------------------------------------

sol = SolutionDimless("airish.yaml")

y_p = model.num_y_plus
U_h = model.fn_U_g(*model.args_charging)
U_c = model.fn_U_g(*model.args_discharging)

sol.set_state(model.num_T_h, 101325, "N2: 0.79, O2: 0.21")
calc_h = WallGradingCalculator.from_solution(sol, L=model.num_D_h, U=U_h)

sol.set_state(model.num_T_c, 101325, "N2: 0.79, O2: 0.21")
calc_c = WallGradingCalculator.from_solution(sol, L=model.num_D_h, U=U_c)

def f_lam(Re):
    return SkinFrictionFactor.laminar(Re) / 8

def f_tur(Re):
    return SkinFrictionFactor.smooth_wall(Re, check=False) / 8

def evaluate_calc(calc):
    y_lam = 1000 * calc.first_layer(y_p, skin_factor=f_lam)
    y_tur = 1000 * calc.first_layer(y_p, skin_factor=f_tur)
    # print(f"Laminar {y_lam:.2f} mm | Turbulent {y_tur:.2f}")
    return y_lam, y_tur

evaluate_calc(calc_c)
y_cell = evaluate_calc(calc_h)[1] / 2

# ---------------------------------------------------------------------------

model.tabulate()
```

## Evaluation procedure

```{python}
%%md
The total required cross-sectional area of solid material in the thermocline $A_t$ is approximately ${model.fn_A_t(*model.args_charging):.1f}\:\mathrm{m^2}$.

$$
A_t = {sp.latex(model.A_t.simplify()):s}
$$

That requires a system diameter of {model.num_D_sys:.1f} m for the considered cell geometry and parameters. Dividing this by the cross-section of solid material in each hexagonal cell gives the number of cells per cross section, which allows for calculating the power per unit cell $P_c$ during charging to be ${model.fn_P_c(*model.args_charging):.0f}\:\mathrm{W}$ and discharging at ${model.fn_P_c(*model.args_discharging):.0f}\:\mathrm{W}$.

$$
P_c = {sp.latex(model.P_c.simplify()):s}
$$

That is equivalent to saying that there should be a total of ${model.fn_N_c(*model.args_charging):.0f}$ cells, with $N_c$ being given by

$$
N_c = {sp.latex(model.N_c.simplify()):s}
$$

During charging, the fluid injection velocity $U$ through the holes in the hexagonal cell is ${U_h:.1f}\:\mathrm{m\,s^{-1}}$, dropping to barely ${U_c:.1f}\:\mathrm{m\,s^{-1}}$ during discharging. That allows for calculating the Reynolds number for fluid flow through the holes in the hexagonal cell. For charging its value is estimated to be in the order of $Re_c \approx {model.fn_Re(*model.args_charging):.0f}$, while for discharging it drops to around $Re_d \approx {model.fn_Re(*model.args_discharging):.0f}$, characterizing a transitional flow regime that should transition to turbulent due to buoyancy effects. Assuming a $y_{+}={model.num_y_plus:.0f}$, one can estimate the first cell center to be at ${y_cell:.2f}\:\mathrm{mm}$, what would be adequate for use with a $k-\omega$ SST model.

$$
U = {sp.latex(model.U_g.simplify()):s}
$$

Assuming a roughness of {eps*1000:.1f} mm, thus a relative roughness of {rel:.3f} for the considered hole diameter. Pressure drop can be estimated using the Darcy-Weisbach equation to be in the order of {dp_charging/100:.0f} mbar during charging and {dp_discharging/100:.1f} mbar during discharging.

With the considered cell geometry, the surface-to-volume ratio $S_V$ of the hexagonal cell is ${model.fn_S_V(*model.args_charging):.3f}\:\mathrm{m^{-1}}$.

$$
S_V = {sp.latex(model.S_V.simplify()):s}
$$

Below we display the surface-to-volume ratio of the hexagonal cell as a function of the diameter of holes and the fraction of diameter representing wall thickness.
```

```{python}
#| fig-cap: Surface-to-volume ratio of the hexagonal cell
#| fig-align: center
#| out-width: 80%
p = tc.plot_surface_to_volume_ratio(model.cell_block)
```

Similarly, the pressure drop across the height of the thermocline can be estimated as a function of the diameter of holes and the fraction of diameter representing wall thickness. Below we display the pressure drop during charging as a function of these parameters.

```{python}
#| fig-cap: Pressure drop across the height of the thermocline during charging
#| fig-align: center
#| out-width: 80%
def dp_scan(D_h, m_h, f=f):
    # Heating is more critical:
    args = [
        # ThermoclineDescription
        model.num_H_t,
        model.num_h_t,
        model.num_T_h,
        model.num_T_c,
        # HexagonalCell
        D_h, # Overrides for funtion
        m_h, # Overrides for funtion
        # SolidMaterial
        model.num_rho_s,
        model.num_c_ps,
        model.num_k_s,
        # OperatingFluid
        model.num_h_g_c,
        model.num_h_g_h,
        # Charging parameters
        model.num_P_c,
        model.num_rho_g_h,
        model.num_mu_g_h
    ]

    rho = args[-2]
    v   = model.fn_U_g(*args)

    calc = tc.PressureDropCalculator(model.num_h_t, D_h)
    return calc.darcy_weisbach_pressure_drop(rho, v, f=f)

p = tc.plot_pressure_drop(dp_scan)
```

# Geometry and mesh

## Mesh generation

The most important parameters for the mesh is the height of the first layer to be used. This is computed based on the expected flow conditions and the desired y+ value for the first layer. The `compute_first_layer` function takes care of this calculation, using the `ThermoclineModel` to get the necessary flow parameters and the `WallGradingCalculator` to compute the first layer thickness.

```{python}
#| echo: true
def compute_first_layer(config: str) -> float:
    """ Compute the first layer thickness for the charging case. """
    model = ThermoclineModel(config)

    y_p = model.num_y_plus
    U_h = model.fn_U_g(*model.args_charging)

    sol = SolutionDimless("airish.yaml")
    sol.set_state(model.num_T_h, 101325, "N2: 0.79, O2: 0.21")
    calc = WallGradingCalculator.from_solution(sol, L=model.num_D_h, U=U_h)

    def f_tur(Re):
        return SkinFrictionFactor.smooth_wall(Re, check=False) / 8

    return calc.first_layer(y_p, skin_factor=f_tur)
```

Function `generate_mesh` is responsible for creating the mesh using the `CowperLikeGeometry` class. It makes use of `compute_first_layer` to get the first layer thickness, and then it creates the geometry and mesh based on the parameters defined in the configuration file. Please notice that if changing any configuration in `dimensioning.yaml`, it may be necessary to change the coefficients multiplying `y_first` and other boundary layer parameters used in this function.

```{python}
#| echo: true
def generate_mesh(config: str, mesh: str, render: bool = False) -> None:
    """ Generate the mesh and conditions for the charging case. """
    y_first = compute_first_layer(config)

    data = YAML().load(open(config))

    geom = CowperLikeGeometry(
        m_h = data["m_h"],
        D_h = data["D_h"],
        h_t = data["h_t"],

        # Use with care based on the above values:
        num_points_angular   = data["num_points_angular"],
        num_points_core      = data["num_points_core"],
        core_radius_fraction = data["core_radius_fraction"],
        fluid_bl_tot         = data["fluid_bl_tot"] * y_first,
        fluid_bl_ext         = data["fluid_bl_ext"] * y_first,
        fluid_bl_int         = data["fluid_bl_int"] * y_first,
        solid_bl_ext         = data["solid_bl_ext"] * y_first,
        solid_bl_int         = data["solid_bl_int"] * y_first,
        rel_layer            = data["rel_layer"],
    )

    geom.create_model(saveas=mesh, render=render)
```

Below we generate the mesh if it does not exist. This is a safety check to prevent accidental overwriting of existing meshes, which can be time-consuming to generate. If you want to generate a new mesh, please make sure to clean the previous mesh and residuals as mentioned in the note above. Setting render to `True` can be useful for debugging purposes, but it is not necessary if you inspect the mesh externally.

```{python}
#| echo: true
if not Path(mesh).exists():
    generate_mesh(config, mesh, render=False)
```

## Mesh conversion for OpenFOAM

So far you could have worked in vanilla Windows, as it supports Gmsh. However, the post-processing steps to convert the mesh for use in OpenFOAM are only implemented for Linux systems, as they rely on OpenFOAM utilities that are not available on Windows. If you are using Windows, you can still generate the mesh, but you will need to transfer it to a Linux system to perform the post-processing steps. This is useful if your local station runs Windows but you have access to a Linux server or a virtual machine/WSL where you can run OpenFOAM.

To avoid generating the mesh again for the full case, we can compress the mesh regions into tarballs. The `compress_region` function takes care of this by creating a tarball for a given region (fluid or solid) that can be later extracted on the Linux system.

```{python}
#| echo: true
def compress_region(case_path: str, region: str) -> None:
    """ Compress a region into a tarball for later use. """
    root_dir = f"{case_path}/constant/{region}/polyMesh"
    mesh_name = f"mesh_{region}"
    shutil.make_archive(mesh_name, "xztar", root_dir=root_dir)
```

Now we can finally convert the mesh for use in OpenFOAM:

1. We use `gmshToFoam` to convert the Gmsh mesh into OpenFOAM format.
2. We use `createPatch` to create the necessary patches for the case.
3. We use `renumberMesh` to optimize the mesh for better performance.
4. We use `splitMeshRegions` to split the mesh cell zones into separate regions.
5. Finally, we compress the fluid and solid regions into tarballs.

```{python}
#| echo: true
def convert_global_mesh(mesh) -> None:
    if sys.platform != "linux":
        raise NotImplementedError("Only implemented for Linux systems.")

    targets = [
        HERE / "mesh_fluid.tar.xz",
        HERE / "mesh_solid.tar.xz",
        HERE / "mesh_zero.tar.xz"
    ]
    if all(target.exists() for target in targets):
        print("Target files already exist.")
        return

    # Run from case directory:
    wdir = HERE / "01-fluid-only"

    # Create the mesh for the hole system:
    runner(["gmshToFoam", HERE / mesh], wdir=wdir)
    runner(["createPatch"], wdir=wdir)
    runner(["renumberMesh"], wdir=wdir)
    runner(["splitMeshRegions", "-cellZones"], wdir=wdir)

    runner(["checkMesh", "-region", "fluid"], wdir=wdir)
    runner(["checkMesh", "-region", "solid"], wdir=wdir)

    compress_region(str(wdir), "fluid")
    compress_region(str(wdir), "solid")

    mesh_zero = wdir / "0.00000000e+00"
    shutil.make_archive("mesh_zero", "xztar", root_dir=mesh_zero)
```

The above function is called below:

```{python}
#| echo: true
convert_global_mesh(mesh)
```

## Extracting the fluid region

The final step is to extract the fluid region from the full mesh. This involves moving the fluid region to the correct location, removing the solid region, and fixing the boundary conditions for the coupled patch. The `post_process_mesh` function takes care of all these steps.

```{python}
#| echo: true
def post_process_mesh(mesh: str) -> None:
    """ Post-process the mesh for use in OpenFOAM. """
    if sys.platform != "linux":
        raise NotImplementedError("Only implemented for Linux systems.")

    # Run from case directory:
    wdir = HERE / "01-fluid-only"

    if (target := HERE / "mesh_single.tar.xz").exists():
        print("Target file already exists.")

        with tarfile.open(target, "r:xz") as tar:
            tar.extractall(path=wdir / "constant/polyMesh")

        return

    # Transform into fluid-only case by extracing the fluid region:
    runner([
        "rm",
        "-rf",
        "0.00000000e+00",
        "constant/polyMesh",
        "constant/solid",
        "constant/cellToRegion",
        "constant/fluid/polyMesh/cellRegionAddressing",
        "constant/fluid/polyMesh/faceRegionAddressing",
        "constant/fluid/polyMesh/pointRegionAddressing"
    ], wdir=wdir)

    runner(["mv", "constant/fluid/polyMesh", "constant/polyMesh"], wdir=wdir)
    runner(["rm", "-rf", "constant/fluid"], wdir=wdir)

    def fix_coupled_patch(patch: str, param: str, *actions) -> None:
        """ Fix the patch type for a given patch. """
        runner([
            "foamDictionary",
            "constant/polyMesh/boundary",
            "-entry", f"entry0/{patch}/{param}",
            *actions
        ], wdir=wdir)

    fix_coupled_patch("fluid_to_solid", "type", "-set", "wall")
    fix_coupled_patch("fluid_to_solid", "inGroups", "-remove")
    fix_coupled_patch("fluid_to_solid", "neighbourRegion", "-remove")
    fix_coupled_patch("fluid_to_solid", "neighbourPatch", "-remove")

    runner(["checkMesh"], wdir=wdir)

    mesh_single = wdir / "constant/polyMesh"
    shutil.make_archive("mesh_single", "xztar", root_dir=mesh_single)
```

The following cell calls the above function to perform the post-processing steps on the mesh. This will prepare the mesh for use in the fluid-only case, which will be used as the initial condition for the coupled case.

```{python}
#| echo: true
post_process_mesh(mesh)
```

# Fluid only case

```bash
01-fluid-only/
├── 0.orig
│   ├── T
│   ├── U
│   └── p
├── Allclean
├── Allrun
├── constant
│   ├── momentumTransport
│   ├── physicalProperties
│   └── userParameters
└── system
    ├── controlDict
    ├── createPatchDict
    ├── decomposeParDict
    ├── functions
    ├── fvConstraints
    ├── fvSchemes
    └── fvSolution
```

```{python}
#| echo: true
case_dir = HERE / "01-fluid-only"
post = PostProcessing(case_dir, mode="charging")
```

## Tabular post-processing

```{python}
post.plot_inlet_mass_flow_rate()
```

```{python}
post.plot_imbalance_mass_flow_rate()
```

```{python}
post.plot_total_pressure()
```

```{python}
post.plot_pressure_drop()
```

```{python}
post.plot_total_temperature()
```

```{python}
post.plot_y_plus()
```

## Field post-processing

```{python}
# runner(["reconstructPar", "-latestTime"], wdir=case_dir)
# runner(["foamLog", "log.foamRun"], wdir=case_dir)
# post.plot_convergence()
```

```{python}
post.plot_field_pressure()
```

```{python}
post.plot_field_density()
```

```{python}
post.plot_field_velocity()
```

```{python}
post.plot_field_temperature()
```

# Including turbulence

```bash
02-fluid-only/
├── 0.orig
│   ├── T
│   ├── U
│   ├── alphat
│   ├── k
│   ├── nut
│   ├── omega
│   └── p
├── Allclean
├── Allrun
├── constant
│   ├── momentumTransport
│   ├── physicalProperties
│   └── userParameters
├── inspect.py
└── system
    ├── controlDict
    ├── createPatchDict
    ├── decomposeParDict
    ├── functions
    ├── fvConstraints
    ├── fvSchemes
    └── fvSolution
```

```{python}
#| echo: true
case_dir = HERE / "02-fluid-only"
post = PostProcessing(case_dir, mode="charging")
```

## Tabular post-processing

```{python}
post.plot_inlet_mass_flow_rate()
```

```{python}
post.plot_imbalance_mass_flow_rate()
```

```{python}
post.plot_total_pressure()
```

```{python}
post.plot_pressure_drop()
```

```{python}
post.plot_total_temperature()
```

```{python}
post.plot_y_plus()
```

## Field post-processing

```{python}
# runner(["reconstructPar", "-latestTime"], wdir=case_dir)
# runner(["foamLog", "log.foamRun"], wdir=case_dir)
# post.plot_convergence()
```

```{python}
post.plot_field_pressure()
```

```{python}
post.plot_field_density()
```

```{python}
post.plot_field_velocity()
```

```{python}
post.plot_field_temperature()
```

# Including buoyancy effects

```bash
03-fluid-only/
├── 0.orig
│   ├── T
│   ├── U
│   ├── alphat
│   ├── k
│   ├── nut
│   ├── omega
│   ├── p
│   └── p_rgh
├── Allclean
├── Allrun
├── constant
│   ├── g
│   ├── momentumTransport
│   ├── physicalProperties
│   └── userParameters
└── system
    ├── controlDict
    ├── createPatchDict
    ├── decomposeParDict
    ├── functions
    ├── fvConstraints
    ├── fvSchemes
    └── fvSolution
```

```{python}
#| echo: true
case_dir = HERE / "03-fluid-only"
post = PostProcessing(case_dir, mode="charging")
```

## Tabular post-processing

```{python}
post.plot_inlet_mass_flow_rate()
```

```{python}
post.plot_imbalance_mass_flow_rate()
```

```{python}
post.plot_total_pressure()
```

```{python}
post.plot_pressure_drop()
```

```{python}
post.plot_total_temperature()
```

```{python}
post.plot_y_plus()
```

## Field post-processing

```{python}
# runner(["reconstructPar", "-latestTime"], wdir=case_dir)
# runner(["foamLog", "log.foamRun"], wdir=case_dir)
# post.plot_convergence()
```

```{python}
post.plot_field_pressure()
```

```{python}
post.plot_field_density()
```

```{python}
post.plot_field_velocity()
```

```{python}
post.plot_field_temperature()
```

```{python}
post.plot_field_buoyancy_pressure()
```

# Adding solid region

```bash
04-fluid-solid/
├── 0.orig
│   ├── fluid
│   │   ├── T
│   │   ├── U
│   │   ├── alphat
│   │   ├── k
│   │   ├── nut
│   │   ├── omega
│   │   ├── p
│   │   └── p_rgh
│   └── solid
│       └── T
├── Allclean
├── Allrun
├── constant
│   ├── fluid
│   │   ├── g
│   │   ├── momentumTransport
│   │   └── physicalProperties
│   ├── solid
│   │   └── physicalProperties
│   └── userParameters
└── system
    ├── controlDict
    ├── createPatchDict
    ├── decomposeParDict
    ├── fluid
    │   ├── fvConstraints
    │   ├── fvSchemes
    │   └── fvSolution
    ├── functions
    ├── fvSolution
    └── solid
        ├── fvSchemes
        └── fvSolution
```

```{python}
#| echo: true
case_dir = HERE / "04-fluid-solid"
post = PostProcessing(case_dir, mode="charging", domain="all")
```

## Tabular post-processing

```{python}
post.plot_inlet_mass_flow_rate()
```

```{python}
post.plot_imbalance_mass_flow_rate()
```

```{python}
post.plot_total_pressure()
```

```{python}
post.plot_pressure_drop()
```

```{python}
post.plot_total_temperature()
```

```{python}
post.plot_y_plus()
```

## Field post-processing

```{python}
# runner(["reconstructPar", "-latestTime"], wdir=case_dir)
# runner(["foamLog", "log.foamMultiRun"], wdir=case_dir)
# post.plot_convergence()
```

```{python}
post.plot_field_pressure()
```

```{python}
post.plot_field_density()
```

```{python}
post.plot_field_velocity()
```

```{python}
post.plot_field_temperature(show_solid=False, show_fluid=True)
```

```{python}
post.plot_field_temperature(show_solid=True, show_fluid=False)
```

# Parametric model

```{python}
# model = ThermoclineModel(config)
# make_solid(model)
# make_charging(model)
```

# References {.unnumbered}

::: {#refs}
:::