#!/usr/bin/env bash

# Run from this directory:
cd ${0%/*} || exit 1

# To open with ParaView:
touch case.foam

if [ ! -d constant/polyMesh ]; then
    (
        # Copy initial conditions:
        cp -avr 0.orig/ 0/

        # Convert base Gmsh mesh to OpenFOAM:
        gmshToFoam constant/domain.msh

        # Perform preliminary renumbering:
        renumberMesh

        # Fix patches types:
        file=constant/polyMesh/boundary
        foamDictionary $file -entry entry0/front/type -set wedge
        foamDictionary $file -entry entry0/back/type  -set wedge
        foamDictionary $file -entry entry0/wall/type  -set wall

        # Check global mesh:
        checkMesh
    ) &> log.initialize
else
    echo "Case already initialized, run Allclean before reinitializing."
fi