[project]
name = "dustmeltingpipe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gmsh>=4.15.2",
    "ipython>=9.16.1",
    "majordome-build",
    "polars>=1.43.2",
]

[tool.uv.sources.majordome-build]
git = "https://github.com/wallytutor/majordome-build.git"
branch = "main"
