#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch case.foam

cp -avr zero/* .

cp ../components/blockMeshDict system/
cp ../components/fv* system/

cp -avr zero/ 0/

runApplication blockMesh

runApplication potentialFoam

runApplication foamRun

#------------------------------------------------------------------------------
