# Generated by Gemini 3.5 Flash to help extract contents.

import re
from pathlib import Path
from bs4 import BeautifulSoup, NavigableString, Tag, Comment


def escape_text(t: str) -> str:
    # Normalize whitespace (replace newlines/tabs with single space)
    t = t.replace("\r\n", "\n").replace("\r", "\n")
    t = re.sub(r'[ \t\n]+', ' ', t)

    # Escape Typst special syntax characters
    t = t.replace("\\", "\\\\")
    t = t.replace("$", "\\$")
    t = t.replace("_", "\\_")
    t = t.replace("*", "\\*")
    t = t.replace("#", "\\#")
    t = t.replace("<", "\\<")
    t = t.replace(">", "\\>")
    t = t.replace("@", "\\@")
    return t


def html_to_typst(
    element, is_chapter_file: bool, footnote_map: dict
) -> str:
    if isinstance(element, Comment):
        return ""
    if isinstance(element, NavigableString):
        return escape_text(str(element))

    if not isinstance(element, Tag):
        return ""

    tag_name = element.name

    # Crosslinks / navigation / section TOCs
    if tag_name == "div":
        classes = [c.lower() for c in element.get("class", [])]
        if any(c in classes for c in ["crosslinks", "sectiontocs"]):
            return ""

    # Footnote marker
    if tag_name == "span" and "footnote-mark" in element.get("class", []):
        a_tag = element.find("a")
        if a_tag:
            href = a_tag.get("href", "")
            frag = href.split("#")[-1] if "#" in href else href
            if frag in footnote_map:
                footnote_text = footnote_map[frag]
                return f"#footnote[{footnote_text}]"
        return ""

    # Inline equation image
    if tag_name == "img":
        cls = element.get("class", [])
        alt = element.get("alt", "")
        if "math" in cls or alt == "eqn":
            return " $T B D$ "
        return ""

    # Quote block
    if tag_name == "div" and "quote" in element.get("class", []):
        quote_p = element.find("p", class_="noindent")
        quote_text = ""
        if quote_p:
            quote_text = "".join(
                html_to_typst(c, is_chapter_file, footnote_map)
                for c in quote_p.children
            ).strip()

        flushright = element.find("div", class_="flushright")
        attribution_text = ""
        if flushright:
            attr_p = flushright.find("p")
            if attr_p:
                attribution_text = "".join(
                    html_to_typst(c, is_chapter_file, footnote_map)
                    for c in attr_p.children
                ).strip()

        # In Typst, quote attribution is specified inside citation
        # or attribution parameter
        if attribution_text:
            return (
                f"\n#quote(block: true, attribution: [{attribution_text}])"
                f"[ {quote_text} ]\n"
            )
        else:
            return f"\n#quote(block: true)[ {quote_text} ]\n"

    # Equation block
    equation_classes = [
        "equation",
        "equation-star",
        "align",
        "subequations",
        "math-display",
        "gather",
        "gather-star",
    ]
    is_eq_block = tag_name in ["table", "div", "center"] and any(
        cls in element.get("class", []) or cls == tag_name
        for cls in equation_classes
    )
    if is_eq_block:
        return "\n$ T B D $\n"

    # Headings
    if tag_name in ["h2", "h3", "h4", "h5"]:
        title_mark = element.find(class_="titlemark")
        if title_mark:
            title_mark.decompose()

        title_text = "".join(
            html_to_typst(c, is_chapter_file, footnote_map)
            for c in element.children
        ).strip()
        title_text = re.sub(r'\s+', ' ', title_text)

        if tag_name == "h2":
            level = 1 if is_chapter_file else 2
        elif tag_name == "h3":
            level = 3
        else:
            level = 4

        heading_prefix = "=" * level
        return f"\n{heading_prefix} {title_text}\n"

    # Paragraphs
    if tag_name == "p":
        parent_name = element.parent.name if element.parent else ""
        content = "".join(
            html_to_typst(c, is_chapter_file, footnote_map)
            for c in element.children
        ).strip()
        if parent_name == "li":
            return content
        else:
            if "center" in element.get("class", []):
                # Skip figures
                imgs = element.find_all("img")
                if imgs and all(
                    "math" not in img.get("class", [])
                    and img.get("alt", "") != "eqn"
                    for img in imgs
                ):
                    return ""
            return f"\n{content}\n"

    # Lists
    if tag_name == "ul":
        content = (
            "\n"
            + "".join(
                html_to_typst(c, is_chapter_file, footnote_map)
                for c in element.children
            )
            + "\n"
        )
        return content
    if tag_name == "ol":
        content = (
            "\n"
            + "".join(
                html_to_typst(c, is_chapter_file, footnote_map)
                for c in element.children
            )
            + "\n"
        )
        return content
    if tag_name == "li":
        content = "".join(
            html_to_typst(c, is_chapter_file, footnote_map)
            for c in element.children
        ).strip()
        prefix = (
            "- "
            if element.parent and element.parent.name == "ul"
            else "+ "
        )
        return f"{prefix}{content}\n"

    # Bold and Italics
    is_italic = tag_name in ["i", "em"] or any(
        "ec-mlmri" in cls or "ec-mlmut" in cls
        for cls in element.get("class", [])
    )
    is_bold = tag_name in ["b", "strong"] or any(
        "ec-mlmb" in cls for cls in element.get("class", [])
    )

    if is_italic and is_bold:
        content = "".join(
            html_to_typst(c, is_chapter_file, footnote_map)
            for c in element.children
        ).strip()
        return f"_*{content}*_"
    elif is_italic:
        content = "".join(
            html_to_typst(c, is_chapter_file, footnote_map)
            for c in element.children
        ).strip()
        return f"_{content}_"
    elif is_bold:
        content = "".join(
            html_to_typst(c, is_chapter_file, footnote_map)
            for c in element.children
        ).strip()
        return f"*{content}*"

    # Links
    if tag_name == "a":
        href = element.get("href", "")
        content = "".join(
            html_to_typst(c, is_chapter_file, footnote_map)
            for c in element.children
        ).strip()
        if href.startswith("http") or href.startswith("mailto"):
            return f'#link("{href}")[{content}]'
        else:
            return content

    # Line break
    if tag_name == "br":
        return " \\ "

    # Center-aligned containers (skip figures)
    if tag_name == "div" and "center" in element.get("class", []):
        imgs = element.find_all("img")
        if imgs and all(
            "math" not in img.get("class", [])
            and img.get("alt", "") != "eqn"
            for img in imgs
        ):
            return ""
        return "".join(
            html_to_typst(c, is_chapter_file, footnote_map)
            for c in element.children
        )

    return "".join(
        html_to_typst(c, is_chapter_file, footnote_map)
        for c in element.children
    )


def extract_footnotes(soup) -> dict:
    footnote_map = {}
    footnote_divs = soup.find_all("div", class_="footnote-text")
    for div in footnote_divs:
        a = div.find("a")
        if not a:
            continue
        frag_id = a.get("id") or a.get("name")
        if not frag_id:
            continue

        mark_span = div.find(class_="footnote-mark")
        if mark_span:
            mark_span.decompose()

        text = "".join(
            html_to_typst(c, False, {}) for c in div.children
        ).strip()
        footnote_map[frag_id] = text

    for div in footnote_divs:
        div.decompose()
    for hr in soup.find_all(
        "hr", class_=["footnote-top", "footnote-bottom"]
    ):
        hr.decompose()

    return footnote_map


def clean_typst_output(content: str) -> str:
    # Remove multiple blank lines
    content = re.sub(r'\n{3,}', '\n\n', content)
    # Remove leading/trailing space in lines
    lines = [line.strip() for line in content.split('\n')]
    # Reassemble
    content = '\n'.join(lines)
    # Remove extra spaces in text
    content = re.sub(r' +', ' ', content)
    # Ensure equation block formatting is correct
    content = content.replace("\n$\n", "\n$ ")
    content = content.replace("\n$\n", " $\n")
    return content.strip() + "\n"


def parse_toc(contents_path: Path) -> list:
    with open(contents_path, "r", encoding="utf-8") as f:
        soup = BeautifulSoup(f.read(), "html.parser")

    toc_div = soup.find(class_="tableofcontents")
    if not toc_div:
        raise ValueError("tableofcontents class not found in contents file.")

    chapters = []
    current_chapter = None

    for child in toc_div.children:
        if child.name == "span":
            cls = child.get("class", [])
            a = child.find("a")
            if not a:
                continue
            href = a.get("href", "")
            title = a.get_text(strip=True)

            if "chapterToc" in cls:
                num_text = child.get_text(strip=True).split(title)[0].strip()
                current_chapter = {
                    "type": "chapter",
                    "number": num_text,
                    "title": title,
                    "file": href,
                    "sections": [],
                }
                chapters.append(current_chapter)
            elif "likechapterToc" in cls:
                if href == "bookindex":
                    continue
                current_chapter = {
                    "type": "likechapter",
                    "title": title,
                    "file": href,
                    "sections": [],
                }
                chapters.append(current_chapter)
            elif "sectionToc" in cls:
                num_text = child.get_text(strip=True).split(title)[0].strip()
                if current_chapter:
                    current_chapter["sections"].append(
                        {"number": num_text, "title": title, "file": href}
                    )
    return chapters


def process_chapter(ch: dict, base_dir: Path, output_dir: Path):
    filename = ch["file"]
    if ch["type"] == "likechapter":
        out_name = f"_{filename}.typ"
    else:
        out_name = f"_chapter{ch['number']}.typ"

    print(f"Processing {ch['title']} -> {out_name}...")

    chapter_content_pieces = []

    # Process chapter file first
    ch_path = base_dir / filename
    if ch_path.exists():
        with open(ch_path, "r", encoding="utf-8") as f:
            ch_soup = BeautifulSoup(f.read(), "html.parser")

        note_div = ch_soup.find(class_="note") or ch_soup
        footnote_map = extract_footnotes(note_div)
        piece = html_to_typst(
            note_div, is_chapter_file=True, footnote_map=footnote_map
        )
        chapter_content_pieces.append(piece)
    else:
        print(f"  Warning: chapter file {ch_path} does not exist.")

    # Process each section file and append
    for sec in ch["sections"]:
        sec_path = base_dir / sec["file"]
        if sec_path.exists():
            with open(sec_path, "r", encoding="utf-8") as f:
                sec_soup = BeautifulSoup(f.read(), "html.parser")

            note_div = sec_soup.find(class_="note") or sec_soup
            footnote_map = extract_footnotes(note_div)
            piece = html_to_typst(
                note_div, is_chapter_file=False, footnote_map=footnote_map
            )
            chapter_content_pieces.append(piece)
        else:
            print(f"  Warning: section file {sec_path} does not exist.")

    # Combine and clean Typst output
    combined = "\n\n".join(chapter_content_pieces)
    cleaned = clean_typst_output(combined)

    # Write to sandbox
    out_path = output_dir / out_name
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(cleaned)


def main():
    # Use Path(__file__).resolve().parent to get the current directory
    current_dir = Path(__file__).resolve().parent
    base_dir = (
        current_dir
        / "download"
        / "doc.cfd.direct"
        / "notes"
        / "cfd-general-principles"
    )
    contents_path = base_dir / "contents"
    output_dir = current_dir / "sandbox"

    output_dir.mkdir(parents=True, exist_ok=True)

    chapters = parse_toc(contents_path)
    print(
        f"Parsed {len(chapters)} chapters/preambles from Table of Contents."
    )

    for ch in chapters:
        process_chapter(ch, base_dir, output_dir)

    print("\nAll chapters successfully extracted under the sandbox directory.")


if __name__ == "__main__":
    main()
