#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch case.foam

cp ../components/blockMeshDict system/blockMeshDict

cp -avr zero/ 0/

runApplication blockMesh

runApplication potentialFoam

rm -rf 0/phi

runApplication foamRun

#------------------------------------------------------------------------------
