#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch case.foam

[ -d "0/" ] && rm -rf "0/"
cp -avr "0.orig/" "0/"

runApplication blockMesh

runApplication foamRun

runApplication foamToVTK

if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

gnuplot << EOF
    set terminal pngcairo color enhanced
    set output "result-T.png"
    set xlabel "Time / [s]"
    set ylabel "Temperature / [K]"
    set grid
    set key right top
    # set xrange [0:10]
    # set yrange [997:1000]
    # set ytics 0.5
    plot "postProcessing/probe/0.000000e+00/T" \\
        t "OpenFOAM" w lines lt 1
EOF

gnuplot << EOF
    set terminal pngcairo color enhanced
    set output "result-P.png"
    set xlabel "Time / [s]"
    set ylabel "Pressure / [Pa]"
    set grid
    set key right top
    # set xrange [0:10]
    # set yrange [101000:101350]
    # set ytics 50
    plot "postProcessing/probe/0.000000e+00/p" \\
        t "OpenFOAM" w lines lt 1
EOF

#------------------------------------------------------------------------------