#!/usr/bin/env bash

##############################################################################
# Common aliases
##############################################################################

# Move to the main directory:
alias fd='cd $FOAM_KOMPANION_DIR'

# Source this file again:
alias fsrc="source ${FOAM_KOMPANION_ETC}/bashrc"

# Re-source the main user bashrc:
alias rsrc="source ${HOME}/.bashrc"

# Disk usage inspection:
alias df="df -HT"

# Disk usage per directory/folder:
alias du="du -h --max-depth=1"

# Alias for listing directory contents:
alias ll='ls -Alh --group-directories-first | sort -k9 -V -r'
alias ls='ls -lh --group-directories-first'

# Aliases for screen (a CFD must-have):
alias scl="screen -ls"
alias scx="screen -x"
alias scs="screen -S"
alias scr="screen -r"

# Make Python/IPython use uv:
alias py='uv run python'
alias ipy='uv run ipython'

##############################################################################
# Apptainer aliases
##############################################################################

alias api="apptainer instance"
alias apl="apptainer instance list"
alias apx="apptainer instance stop"

function apu() {
    local image=$1
    local bind="${2:-/opt/app}"
    local name="${image%.sif}"

    apptainer instance start --writable-tmpfs \
        --bind "$(realpath $PWD):${bind}" "${image}" "${name}"
}

function aps() {
    local name=${1}
    apptainer shell "instance://$name"
}

DEFAULT_NAME="foam-$(whoami)"
DEFAULT_BIND="/home/$(whoami)/foam-$(whoami)"
DEFAULT_IMAGE="$FOAM_KOMPANION_DIR/$DEFAULT_NAME.sif"

function foam_instance_running() {
    local running=$(
        apptainer instance list | awk \
        -v n="${DEFAULT_NAME}" \
        -v i="$(realpath -m "${DEFAULT_IMAGE}")" \
        '$1 == n && $NF == i {print "yes"}'
    )

    echo "$running"
}

function foam_instance_ensure() {
    if [ "$(foam_instance_running)" != "yes" ]; then
        echo "No matching instance ${DEFAULT_NAME} found, starting..."
        foam_instance_start
    fi
}

function foam_instance_start() {
    apptainer instance start --writable-tmpfs \
        --bind "${FOAM_KOMPANION_DIR}:${DEFAULT_BIND}" \
        "${DEFAULT_IMAGE}" "${DEFAULT_NAME}"
}

function foam_instance_stop() {
    if [ "$(foam_instance_running)" = "yes" ]; then
        apptainer instance stop "${DEFAULT_NAME}"
    else
        echo "No matching instance found: ${DEFAULT_NAME}"
    fi
}

function foam_instance_shell() {
    foam_instance_ensure
    apptainer exec "instance://${DEFAULT_NAME}" bash --rcfile ~/.bashrc -i
}

function foam_instance_exec() {
    foam_instance_ensure
    apptainer exec "instance://${DEFAULT_NAME}" "$@"
}

alias fs='foam_instance_shell'
alias fk='foam_instance_stop'
alias fx='foam_instance_exec'

##############################################################################
# Container aliases
##############################################################################

alias pi="podman image"
alias pc="podman container"

alias pil="podman images -a"
alias pcl="podman container ls"
alias pcp="podman container prune"

function pfresh() {
    podman builder prune -a
    podman system prune -a --volumes
}

function pexec() {
    local label=$1

    if [ -z "${label}" ]; then
        echo "Usage: pexec <container-id|container-name>" >&2
        podman container ls
        return 1
    fi

    podman exec -it "${1}" /bin/bash
}

# drun() {
#     docker run -it --rm --gpus all \
#         --mount type=bind,source="$(realpath $PWD)",target=/opt/app \
#         "${1}" "${2:-/bin/bash}"
# }
