#!/usr/bin/env bash

function log_step_counter() {
    local app=$1

    # By setting nullglob, unmatched patterns safely expand to nothing
    # instead of raising an error or returning a literal glob string.
    shopt -s nullglob
    local files=(log."$app"*)
    shopt -u nullglob
    local step=$((${#files[@]} + 1))

    echo "$step"
}

function copyOrigToCase() {
    local target=$1
    cp "$target.orig" "$target"
}

function runApplicationRename() {
    local app=$1
    local step=$(log_step_counter $app)

    runApplication $@
    mv "log.$app" "log.$app.$step"
}

function runParallelRename() {
    local app=$1
    local step=$(log_step_counter $app)

    runParallel $@
    mv "log.$app" "log.$app.$step"
}

function runAndReconstructStep() {
    # Decompose the domain:
    runApplicationRename decomposePar -latestTime

    # Run the simulation:
    runParallelRename foamRun -parallel

    # Reconstruct the solution:
    runApplicationRename reconstructPar -latestTime

    # Remove decomposition files:
    rm -rf processor*
}

function runSnappyHexMeshBasicWorkflow() {
    local parallel=${1:-1}

    # Pre-meshing:
    runApplicationRename blockMesh
    runApplicationRename surfaceFeatures

    # Main meshing:
    if [ $parallel -eq 1 ]; then
        runApplicationRename snappyHexMesh
    else
        runApplicationRename decomposePar -noZero -constant
        runParallelRename snappyHexMesh
    fi

    # Post-meshing:
    runApplicationRename reconstructPar -noZero -constant
    runApplicationRename renumberMesh -noZero -constant
    runApplicationRename checkMesh

    # Remove decomposition files:
    rm -rf processor*
}

function foamStepRunner() {
    local tend=$1
    local parallel=${2:-1}

    if [ $parallel -eq 1 ]; then
        runAndReconstructStep
    else
        runApplicationRename foamRun
    fi

    # Backup before modifying solver settings:
    cp -r "$tend" "$tend.orig"
}
