#!/usr/bin/env bash

# Run from this directory
cd ${0%/*} || exit 1

# ---------------------------------------------------------------------
# Remove top-level time directories like 0.00000000e+00
# ---------------------------------------------------------------------

find . \
    -mindepth 1 -maxdepth 1 -type d \
    -regextype posix-extended \
    -regex './[0-9]+\.[0-9]+e[+-][0-9]+' \
    -exec rm -rf -- {} +

# ---------------------------------------------------------------------
# Specific files
# ---------------------------------------------------------------------

rm -rf case.foam
rm -rf mesh.msh
rm -rf constant/cellToRegion
rm -rf constant/solid/
rm -rf constant/fluid/
rm -rf postProcessing
rm -rf processor*
rm -rf log.*
rm -rf logs
rm -rf __pycache__/

# Here also remove mesh:
rm -rf constant/polyMesh/

# ---------------------------------------------------------------------
# EOF
# ---------------------------------------------------------------------