#!/usr/bin/env bash

# ---------------------------------------------------------------------

# Run from this directory
cd ${0%/*} || exit 1

# Source OpenFOAM environment helpers
source ../../../script/foamrc

# Select number of cores to use for parallel run
export NUM_PROCS=$(safe_run_ncores 20)

# ---------------------------------------------------------------------

# Ensure mesh is present by extracting from archive if not already done
if [ ! -d "constant/polyMesh" ]; then
    mkdir -p constant/polyMesh
    tar -xf ../mesh_single.tar.xz -C constant/polyMesh
fi

# ---------------------------------------------------------------------

# Whether to start from scratch or restart from previous case
mode="restart"

if [ "$mode" = "restart" ]; then
    reference="../01-fluid-only"
    last_time="$(foamListTimes -case "$reference" -latestTime)"

    cp -avr "$reference/$last_time" 0.00000000e+00
    rm -rf 0.00000000e+00/uniform/
else
    # Expand original conditions to actual mesh
    mkdir -p 0.00000000e+00
    foamDictionary 0.orig/p      -expand > 0.00000000e+00/p
    foamDictionary 0.orig/T      -expand > 0.00000000e+00/T
    foamDictionary 0.orig/U      -expand > 0.00000000e+00/U
fi

# Expand turbulence fields to actual mesh
foamDictionary 0.orig/alphat -expand > 0.00000000e+00/alphat
foamDictionary 0.orig/nut    -expand > 0.00000000e+00/nut
foamDictionary 0.orig/k      -expand > 0.00000000e+00/k
foamDictionary 0.orig/omega  -expand > 0.00000000e+00/omega

# ---------------------------------------------------------------------

# Run the case in parallel
decomposePar
mpiexec -n $NUM_PROCS foamRun -parallel > log.foamRun

# Reconstruct the results of final time step
reconstructPar -latestTime

# Generate logs for post-processing
foamLog log.foamRun
