#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch case.foam

cp -avr zero/* .
cp ../components/blockMeshDict system/
cp ../components/fv* system/
cp ../components/Allclean .

runApplication blockMesh
runApplication potentialFoam

rm -rf 0/phi

runApplication foamRun

cp "postProcessing/residuals(p,U,k,epsilon,h)/0/residuals.dat" residuals.ref
tail -24 log.foamRun >> residuals.ref

#------------------------------------------------------------------------------
