#!/usr/bin/env bash

# Run from this directory
cd ${0%/*} || exit 1

# ---------------------------------------------------------------------
# Remove top-level time directories like 0.00000000e+00
# ---------------------------------------------------------------------
find . \
    -mindepth 1 -maxdepth 1 -type d \
	-regextype posix-extended \
	-regex './[0-9]+\.[0-9]+e[+-][0-9]+' \
	-exec rm -rf -- {} +

# ---------------------------------------------------------------------
# Specific files
# ---------------------------------------------------------------------

rm -rf case.foam
rm -rf mesh.msh
rm -rf constant/polyMesh/
rm -rf constant/cellToRegion
rm -rf constant/block/
rm -rf constant/media/polyMesh/
rm -rf system/block/
rm -rf system/media/
rm -rf postProcessing
rm -rf log.*
rm -rf logs

# ---------------------------------------------------------------------
# EOF
# ---------------------------------------------------------------------
