#!/usr/bin/env bash

# Run from this directory
cd ${0%/*} || exit 1

FORCE=0

# PROPS can be "constant" or "tables"
PROPS="tables"

touch case.foam

# ---------------------------------------------------------------------
# Mesh preparation
# ---------------------------------------------------------------------

if [ ! -d constant/block/polyMesh ] ||
   [ ! -d constant/media/polyMesh ] ||
   [ $FORCE -ne 0 ]; then
    echo "Mesh not found or force enabled, preparing mesh..."

    if [ ! -f mesh.msh ] || [ $FORCE -ne 0 ]; then
        echo "Mesh file not found or force enabled, generating mesh..."
        python3 model.py > log.0.meshPy 2>&1
    fi

    # Convert gmsh mesh to OpenFOAM format
    gmshToFoam mesh.msh > log.1.gmshToFoam 2>&1

    # Fix patches that are over directions not used by solution
    foamDictionary constant/polyMesh/boundary \
    -entry entry0/sides_block/type \
    -set empty > log.2.setBoundaryType 2>&1

    foamDictionary constant/polyMesh/boundary \
    -entry entry0/sides_media/type \
    -set empty >> log.2.setBoundaryType 2>&1

    # Prepare and check the mesh for use with region coupling
    renumberMesh > log.3.renumberMesh 2>&1
    splitMeshRegions -cellZones > log.4.splitMeshRegions 2>&1
    rm -rf constant/polyMesh/ > /dev/null 2>&1

    checkMesh -region block > log.5.checkMeshBlock 2>&1
    checkMesh -region media > log.6.checkMeshMedia 2>&1
else
    echo "Mesh already prepared, skipping mesh preparation."
fi

# ---------------------------------------------------------------------
# Copy conditions and run the case
# ---------------------------------------------------------------------

if [ ! -f log.7.foamMultiRun ] || [ $FORCE -ne 0 ]; then
    echo "Case not run or force enabled, preparing case and running..."

    # Expand initial conditions (so that we can plot them):
    foamDictionary 0.orig/block/T -expand > 0.00000000e+00/block/T 2>&1
    foamDictionary 0.orig/media/T -expand > 0.00000000e+00/media/T 2>&1

    # Copy numerical settings for each region:
    if [ ! -d system/block ] || [ $FORCE -ne 0 ]; then
        cp -r template/system system/block/                    > /dev/null 2>&1
        sed -i "s/REGION_NAME/block/g" system/block/fvSolution > /dev/null 2>&1
        sed -i "s/REGION_NAME/block/g" system/block/fvSchemes  > /dev/null 2>&1

    fi

    if [ ! -d system/media ] || [ $FORCE -ne 0 ]; then
        cp -r template/system system/media/                    > /dev/null 2>&1
        sed -i "s/REGION_NAME/media/g" system/media/fvSolution > /dev/null 2>&1
        sed -i "s/REGION_NAME/media/g" system/media/fvSchemes  > /dev/null 2>&1
    fi

    # Copy selected physical properties:
    mkdir -p constant/block/ > /dev/null 2>&1
    properties="constant/block/physicalProperties.${PROPS}"
    cp template/$properties constant/block/physicalProperties > /dev/null 2>&1

    foamMultiRun > log.7.foamMultiRun 2>&1 &
else
    echo "Case already run, skipping case preparation and run."
fi

# ---------------------------------------------------------------------
# EOF
# ---------------------------------------------------------------------